version: '3.8'

services:
  app:
    image: dataneuron-task-2-service-image
    container_name: dataneuron-task-2-service-container
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4000:4000
